### ISSUE TITLE
Fail reading chunked HTML Body with multiple chunks

### ISSUE THREAD

**Issue by ChriD** [Zintinio/HappyHTTP#10]
If there is a HTML Body with mutliple chunks there is a problem parsing the whole data.
The second chunklen info is beeing skipped because the "\r\n" was soaked up (if the second chunkleninfo has no extra "\n" before)

I'm not sure how to fix this without redesigning the whole pump method...

**Comment by ChriD** [comment]
Forget It... I think its my fault!

**Comment by Zintinio** [comment]
ChriD thanks for posting the issue anyway, I'm planning a redesign of HappyHTTP at some point *anyway*...it's just that there's so many *other* projects I'm working on. I don't think having a pump method is the best approach. From what I've seen, I think Microsoft's cpprestsdk is the best "modern" design available right now. I recommend using it.
