### ISSUE TITLE
Support for HTTPS and compile for iOS?

### ISSUE THREAD

**Issue by prsolucoes** [Zintinio/HappyHTTP#18]
Hi,

1 - It has support for HTTPS?
2 - It can be compile to iOS?

Thanks.

**Comment by Zintinio** [comment]
@prsolucoes Check out https://github.com/Alamofire/Alamofire and https://github.com/AFNetworking/AFNetworking for iOS.

Any reason you want to use this on iOS?

**Comment by prsolucoes** [comment]
Im making a native-kit project, that all business-logic and simple tools like sqlite, http client, key-value db will be in single code and exported to swift/objc/java automatically using swig and can be used in desktop apps:

https://github.com/prsolucoes/native-kit

Today im using curl for HttpClient operations. Im only asking about your class an compatibility with HTTPS.

**Comment by Zintinio** [comment]
No support.
