### ISSUE TITLE
Why call WSAStartup(), at struct in_addr *atoaddr( const char* address) ?

### ISSUE THREAD

**Issue by Ushio** [Zintinio/HappyHTTP#19]
Hello!

Why call WSAStartup(), at struct in_addr *atoaddr( const char* address) ?
I found this code in struct in_addr *atoaddr( const char* address) 
```
	// Startup socket
	WSAData data;
	WSAStartup(MAKEWORD(2,0), &data);

```
but I can't find WSACleanup() function call. 
And, on test code contains WSAStartup(), WSACleanup(), but the initialize version is different.
 (test.cpp)

```

#ifdef WIN32
    WSAData wsaData;
    int code = WSAStartup(MAKEWORD(1, 1), &wsaData);
	if( code != 0 )
	{
		fprintf(stderr, "shite. %d\n",code);
		return 0;
	}
#endif //WIN32

// main code~~

#ifdef WIN32
    WSACleanup();
#endif // WIN32


```

What is best initialization?

Thanks.

**Comment by Zintinio** [comment]
@Ushio looking into this right now, seems I merged in some bad code.

**Comment by Zintinio** [comment]
Should be resolved after recent changes.
