### ISSUE TITLE
Using HTTPS with HappyHTTP

### ISSUE THREAD

**Issue by Kladdy** [Zintinio/HappyHTTP#6]

**Comment by ChazUK** [comment]
@Kladdy Did you find a solution for this? I'm struggling to find a C++ HTTP / REST library that isn't C++11

**Comment by Zintinio** [comment]
@ChazUK you'll likely have to use cURL. Last time I tried it on Windows was circa 2012, things might be better now.

**Comment by Kladdy** [comment]
I did not find a solution for this, but I did not search for a long time. Maybe Boost has some HTTPS capabilities?
